/** Canonical seed catalog — picsum seeds are stable & reliable. */
export const SEED_PRODUCTS = [
  {
    name: "Royal Emerald Silk Saree",
    slug: "royal-emerald-silk-saree",
    description: "Handwoven pure silk saree in deep emerald with intricate gold zari border. A timeless piece for weddings and festive occasions. Includes matching blouse fabric.",
    price: 12999,
    compareAtPrice: 15999,
    images: [
      "https://picsum.photos/seed/ahf-emerald-saree-1/800/1000",
      "https://picsum.photos/seed/ahf-emerald-saree-2/800/1000",
    ],
    category: "Sarees",
    fabricType: "Silk",
    sizes: ["Free Size"],
    colors: ["Emerald", "Gold"],
    stock: 25,
    featured: true,
    published: true,
  },
  {
    name: "Ivory Cotton Kurta Set",
    slug: "ivory-cotton-kurta-set",
    description: "Breathable premium cotton kurta with subtle embroidery. Paired with matching trousers. Perfect for everyday elegance and Eid gatherings.",
    price: 3499,
    compareAtPrice: 4299,
    images: [
      "https://picsum.photos/seed/ahf-ivory-kurta-1/800/1000",
      "https://picsum.photos/seed/ahf-ivory-kurta-2/800/1000",
    ],
    category: "Kurtas",
    fabricType: "Cotton",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Ivory", "Cream", "White"],
    stock: 40,
    featured: true,
    published: true,
  },
  {
    name: "Midnight Sherwani",
    slug: "midnight-sherwani",
    description: "Regal navy sherwani with gold threadwork and mandarin collar. Tailored fit with silk lining. Ideal for grooms and wedding guests.",
    price: 24999,
    compareAtPrice: 29999,
    images: [
      "https://picsum.photos/seed/ahf-midnight-sherwani-1/800/1000",
      "https://picsum.photos/seed/ahf-midnight-sherwani-2/800/1000",
    ],
    category: "Sherwanis",
    fabricType: "Silk Blend",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Navy", "Black", "Maroon"],
    stock: 12,
    featured: true,
    published: true,
  },
  {
    name: "Golden Tissue Dupatta",
    slug: "golden-tissue-dupatta",
    description: "Lightweight tissue dupatta with shimmering gold finish and delicate lace edges. Complements sarees and lehengas beautifully.",
    price: 1899,
    compareAtPrice: 2499,
    images: [
      "https://picsum.photos/seed/ahf-golden-dupatta-1/800/1000",
      "https://picsum.photos/seed/ahf-golden-dupatta-2/800/1000",
    ],
    category: "Dupattas",
    fabricType: "Tissue",
    sizes: ["2.5m"],
    colors: ["Gold", "Rose Gold", "Silver"],
    stock: 60,
    featured: false,
    published: true,
  },
  {
    name: "Banarasi Brocade Fabric (Per Meter)",
    slug: "banarasi-brocade-fabric",
    description: "Authentic Banarasi brocade sold by the meter. Rich motifs woven with metallic threads. Ideal for custom lehengas and jackets.",
    price: 2200,
    compareAtPrice: 2800,
    images: [
      "https://picsum.photos/seed/ahf-banarasi-1/800/1000",
      "https://picsum.photos/seed/ahf-banarasi-2/800/1000",
    ],
    category: "Fabrics",
    fabricType: "Brocade",
    sizes: ["1m", "2m", "3m", "5m"],
    colors: ["Red", "Emerald", "Royal Blue"],
    stock: 100,
    featured: true,
    published: true,
  },
  {
    name: "Linen Summer Abaya",
    slug: "linen-summer-abaya",
    description: "Flowing linen abaya with minimalist stitching and soft drape. Comfortable for warm climates while maintaining modest elegance.",
    price: 4599,
    compareAtPrice: 5499,
    images: [
      "https://picsum.photos/seed/ahf-linen-abaya-1/800/1000",
      "https://picsum.photos/seed/ahf-linen-abaya-2/800/1000",
    ],
    category: "Abayas",
    fabricType: "Linen",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Beige", "Black", "Olive"],
    stock: 30,
    featured: false,
    published: true,
  },
  {
    name: "Chanderi Silk Suit Set",
    slug: "chanderi-silk-suit-set",
    description: "Three-piece Chanderi silk suit with embroidered neckline, straight pants, and contrasting dupatta. Lightweight with a luminous finish.",
    price: 6999,
    compareAtPrice: 8499,
    images: [
      "https://picsum.photos/seed/ahf-chanderi-1/800/1000",
      "https://picsum.photos/seed/ahf-chanderi-2/800/1000",
    ],
    category: "Suits",
    fabricType: "Chanderi Silk",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Peach", "Mint", "Lavender"],
    stock: 22,
    featured: true,
    published: true,
  },
  {
    name: "Velvet Embroidered Jacket",
    slug: "velvet-embroidered-jacket",
    description: "Statement velvet jacket with traditional embroidery. Layer over kurtas or western wear for a fusion look at evening events.",
    price: 8999,
    compareAtPrice: 10999,
    images: [
      "https://picsum.photos/seed/ahf-velvet-jacket-1/800/1000",
      "https://picsum.photos/seed/ahf-velvet-jacket-2/800/1000",
    ],
    category: "Jackets",
    fabricType: "Velvet",
    sizes: ["M", "L", "XL"],
    colors: ["Burgundy", "Forest Green", "Black"],
    stock: 8,
    featured: false,
    published: true,
  },
  {
    name: "Handloom Cotton Stole",
    slug: "handloom-cotton-stole",
    description: "Artisan handloom cotton stole with heritage weave patterns. Soft, breathable, and ethically sourced from Indian weavers.",
    price: 999,
    compareAtPrice: 1299,
    images: [
      "https://picsum.photos/seed/ahf-cotton-stole-1/800/1000",
      "https://picsum.photos/seed/ahf-cotton-stole-2/800/1000",
    ],
    category: "Stoles",
    fabricType: "Cotton",
    sizes: ["One Size"],
    colors: ["Indigo", "Mustard", "Terracotta"],
    stock: 75,
    featured: false,
    published: true,
  },
  {
    name: "Bridal Lehenga Fabric Pack",
    slug: "bridal-lehenga-fabric-pack",
    description: "Curated bridal pack: 5m lehenga fabric, 2.5m blouse, and 2.5m dupatta in coordinated heavy embroidery. Ready for your tailor.",
    price: 34999,
    compareAtPrice: 42999,
    images: [
      "https://picsum.photos/seed/ahf-bridal-pack-1/800/1000",
      "https://picsum.photos/seed/ahf-bridal-pack-2/800/1000",
    ],
    category: "Bridal",
    fabricType: "Silk Embroidery",
    sizes: ["Custom"],
    colors: ["Red Gold", "Pink Gold", "Maroon"],
    stock: 5,
    featured: true,
    published: true,
  },
] as const;

export const SEED_COUPONS = [
  { code: "WELCOME10", type: "PERCENT", value: 10, minOrder: 2000, active: true },
  { code: "GOLD500", type: "FIXED", value: 500, minOrder: 5000, active: true },
  { code: "EID15", type: "PERCENT", value: 15, minOrder: 3000, maxUses: 100, active: true },
] as const;
