/** Canonical seed catalog — verified clothing/fabric Unsplash images. */
export const SEED_PRODUCTS = [
  {
    name: "Royal Emerald Silk Saree",
    slug: "royal-emerald-silk-saree",
    description: "Handwoven pure silk saree in deep emerald with intricate gold zari border. A timeless piece for weddings and festive occasions. Includes matching blouse fabric.",
    price: 12999,
    compareAtPrice: 15999,
    images: [
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80",
    ],
    category: "Sarees",
    fabricType: "Silk",
    sizes: ["Free Size"],
    colors: ["Emerald", "Gold"],
    stock: 25,
    featured: true,
    published: true,
  },
  {
    name: "Ivory Cotton Kurta Set",
    slug: "ivory-cotton-kurta-set",
    description: "Breathable premium cotton kurta with subtle embroidery. Paired with matching trousers. Perfect for everyday elegance and Eid gatherings.",
    price: 3499,
    compareAtPrice: 4299,
    images: [
      "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80",
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
    ],
    category: "Kurtas",
    fabricType: "Cotton",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Ivory", "Cream", "White"],
    stock: 40,
    featured: true,
    published: true,
  },
  {
    name: "Midnight Sherwani",
    slug: "midnight-sherwani",
    description: "Regal navy sherwani with gold threadwork and mandarin collar. Tailored fit with silk lining. Ideal for grooms and wedding guests.",
    price: 24999,
    compareAtPrice: 29999,
    images: [
      "https://images.unsplash.com/photo-1593032465175-481ac7f401a0?w=800&q=80",
      "https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800&q=80",
    ],
    category: "Sherwanis",
    fabricType: "Silk Blend",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Navy", "Black", "Maroon"],
    stock: 12,
    featured: true,
    published: true,
  },
  {
    name: "Golden Tissue Dupatta",
    slug: "golden-tissue-dupatta",
    description: "Lightweight tissue dupatta with shimmering gold finish and delicate lace edges. Complements sarees and lehengas beautifully.",
    price: 1899,
    compareAtPrice: 2499,
    images: [
      "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&q=80",
      "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&q=80",
    ],
    category: "Dupattas",
    fabricType: "Tissue",
    sizes: ["2.5m"],
    colors: ["Gold", "Rose Gold", "Silver"],
    stock: 60,
    featured: false,
    published: true,
  },
  {
    name: "Banarasi Brocade Fabric (Per Meter)",
    slug: "banarasi-brocade-fabric",
    description: "Authentic Banarasi brocade sold by the meter. Rich motifs woven with metallic threads. Ideal for custom lehengas and jackets.",
    price: 2200,
    compareAtPrice: 2800,
    images: [
      "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800&q=80",
      "https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&q=80",
    ],
    category: "Fabrics",
    fabricType: "Brocade",
    sizes: ["1m", "2m", "3m", "5m"],
    colors: ["Red", "Emerald", "Royal Blue"],
    stock: 100,
    featured: true,
    published: true,
  },
  {
    name: "Linen Summer Abaya",
    slug: "linen-summer-abaya",
    description: "Flowing linen abaya with minimalist stitching and soft drape. Comfortable for warm climates while maintaining modest elegance.",
    price: 4599,
    compareAtPrice: 5499,
    images: [
      "https://images.unsplash.com/photo-1612423284934-2850a4ea6b0f?w=800&q=80",
      "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80",
    ],
    category: "Abayas",
    fabricType: "Linen",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Beige", "Black", "Olive"],
    stock: 30,
    featured: false,
    published: true,
  },
  {
    name: "Chanderi Silk Suit Set",
    slug: "chanderi-silk-suit-set",
    description: "Three-piece Chanderi silk suit with embroidered neckline, straight pants, and contrasting dupatta. Lightweight with a luminous finish.",
    price: 6999,
    compareAtPrice: 8499,
    images: [
      "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=800&q=80",
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
    ],
    category: "Suits",
    fabricType: "Chanderi Silk",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Peach", "Mint", "Lavender"],
    stock: 22,
    featured: true,
    published: true,
  },
  {
    name: "Velvet Embroidered Jacket",
    slug: "velvet-embroidered-jacket",
    description: "Statement velvet jacket with traditional embroidery. Layer over kurtas or western wear for a fusion look at evening events.",
    price: 8999,
    compareAtPrice: 10999,
    images: [
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80",
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80",
    ],
    category: "Jackets",
    fabricType: "Velvet",
    sizes: ["M", "L", "XL"],
    colors: ["Burgundy", "Forest Green", "Black"],
    stock: 8,
    featured: false,
    published: true,
  },
  {
    name: "Handloom Cotton Stole",
    slug: "handloom-cotton-stole",
    description: "Artisan handloom cotton stole with heritage weave patterns. Soft, breathable, and ethically sourced from Indian weavers.",
    price: 999,
    compareAtPrice: 1299,
    images: [
      "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800&q=80",
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80",
    ],
    category: "Stoles",
    fabricType: "Cotton",
    sizes: ["One Size"],
    colors: ["Indigo", "Mustard", "Terracotta"],
    stock: 75,
    featured: false,
    published: true,
  },
  {
    name: "Bridal Lehenga Fabric Pack",
    slug: "bridal-lehenga-fabric-pack",
    description: "Curated bridal pack: 5m lehenga fabric, 2.5m blouse, and 2.5m dupatta in coordinated heavy embroidery. Ready for your tailor.",
    price: 34999,
    compareAtPrice: 42999,
    images: [
      "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80",
      "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&q=80",
    ],
    category: "Bridal",
    fabricType: "Silk Embroidery",
    sizes: ["Custom"],
    colors: ["Red Gold", "Pink Gold", "Maroon"],
    stock: 5,
    featured: true,
    published: true,
  },
] as const;

export const SEED_COUPONS = [
  { code: "WELCOME10", type: "PERCENT", value: 10, minOrder: 2000, active: true },
  { code: "GOLD500", type: "FIXED", value: 500, minOrder: 5000, active: true },
  { code: "EID15", type: "PERCENT", value: 15, minOrder: 3000, maxUses: 100, active: true },
] as const;
